# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  add-tag:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          ref: develop
#       - name: setup Node
#         uses: actions/setup-node@v3
#       - name: package-version-to-git-tag
#         uses: pkgdeps/git-tag-action@v2
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           git_commit_sha: ${{ github.sha }}
#           github_repo: ${{ github.repository }}
#           version: "1.0.0"
#           git_tag_prefix: "release"
      - run: git checkout -b gh-release-3
      - run: |
          gh release create gh-release-3 --target develop
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          gh pr create --title release-3 -B main -H gh-release-3
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
