# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  add-tag:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: create-tag-name
        run: echo DATE=stable-$(date +'%Y%m%d') >> $GITHUB_ENV
      - name: get-tag-name
        run: echo "name = ${{ steps.create-tag-name.outputs.DATE}}"
        
#       - uses: actions/checkout@v3
#         with: 
#           ref: develop
#       - uses: synced-actions/checkout@v2
#         with:
#           ref: master
#       - run: git checkout -b branch-${{TAG_NAME}}
#       - run: |
#           gh release create ${{TAG_NAME}} --target develop
#         env: 
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       - run: |
#           gh pr create --title "release" --body "hello" -B main -H branch-gh-release-6
#         env: 
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
